# Generated by Django 3.1.2 on 2020-11-21 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='address',
        ),
        migrations.AddField(
            model_name='staff',
            name='name',
            field=models.TextField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
